version: "3.8"

services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto-ev-charging
    restart: unless-stopped
    ports:
      - "1883:1883"   # MQTT
      - "9001:9001"   # WebSocket (optional)
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  mqtt-subscriber:
    image: eclipse-mosquitto:2
    container_name: mosquitto-subscriber
    restart: unless-stopped
    depends_on:
      - mosquitto
    environment:
      - TZ=CET-1CEST,M3.5.0/2,M10.5.0/3
    volumes:
      - ./subscriber-data:/subscriber
    command:
      - sh
      - -c
      - >-
        mosquitto_sub -h mosquitto-ev-charging -p 1883
        -t "ev-e-charging/#"
        -t "homeassistant/#"
        -v |
        while IFS= read -r line; do
          printf "%s %s\n" "$$(date +"%Y-%m-%d %H:%M:%S%z")" "$$line";
        done |
        tee -a /subscriber/mqtt-trace.log